# Generated by Django 4.2.7 on 2025-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(choices=[('mobile', 'Mobile App Development'), ('web', 'Web Development'), ('custom', 'Custom Software'), ('consulting', 'IT Consulting'), ('other', 'Other')], max_length=20)),
                ('budget', models.CharField(choices=[('250-500', '$250 - $500'), ('500-1000', '$500 - $1,000'), ('1000-2500', '$1,000 - $2,500'), ('2500+', '$2,500+')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_spam', models.BooleanField(default=False)),
                ('spam_score', models.FloatField(default=0.0)),
                ('is_read', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
